name: Node CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: |
          make setup
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
